version: '3.5'
services:
  devhoust-backend:
    links:
      - db:db_mysql
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - '13000:13000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: db_mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devhouse
    ports:
      - '3306:3306'
volumes:
  db_data:
